GO
DECLARE @COPAIS VARCHAR(3), @NOMBRE VARCHAR(50)
SET @COPAIS = '99'
SET @NOMBRE = 'PORTUGAL'
--EVALUA SI EXISTE EL REGISTRO DE LA TABLA, SI EXISTE ACTUALIZADO, SINO INSERTO

IF EXISTS(SELECT * FROM VENTA.PAISES WHERE Idpais = @COPAIS)
   BEGIN 
     UPDATE VENTA.PAISES SET NombrePais = @NOMBRE WHERE Idpais = @COPAIS
   END
ELSE 
   BEGIN 
    INSERT INTO VENTA.PAISES VALUES (@COPAIS,@NOMBRE)
   END 
GO

SELECT * FROM VENTA.PAISES