CREATE FUNCTION DBO.MISREPORTES(@val REAL)
RETURNS TABLE
AS
RETURN(SELECT CUS_FNAME AS 'NOMBRE', CUS_LNAME AS 'APELLIDO', CUS_BALANCE AS 'BALANCE' FROM CUSTOMER WHERE CUS_BALANCE > @val)
GO


SELECT * FROM DBO.MISREPORTES(100);
/*---------------------------------------------------------------------------------------------------------------------------------*/

CREATE FUNCTION DBO.SALDO()
RETURNS TABLE
AS
RETURN(SELECT (CUS_FNAME + ' ' + CUS_LNAME) AS NOMBRE, CUS_PHONE AS TELEFONO , CUS_BALANCE AS SALDO FROM CUSTOMER WHERE CUS_BALANCE = 0)
GO

SELECT * FROM DBO.SALDO()

/*---------------------------------------------------------------------------------------------------------------------------------*/

CREATE FUNCTION DBO.FECHA()
RETURNS TABLE
AS
RETURN(SELECT * FROM INVOICE WHERE CUS_CODE = (SELECT CUS_CODE FROM CUSTOMER WHERE CUS_BALANCE = (SELECT MAX(CUS_BALANCE) FROM CUSTOMER)))
GO

SELECT * FROM DBO.FECHA()

/*---------------------------------------------------------------------------------------------------------------------------------*/

CREATE PROCEDURE INSERT_PRODUCT
@P_CODE NVARCHAR(10),@DESCRIP NVARCHAR(35),@FECHA DATETIME,@CANTI SMALLINT, @MIN SMALLINT, @PRECIO REAL, @DESC FLOAT,@V_CODE INT
AS
INSERT INTO PRODUCT
VALUES(@P_CODE,@DESCRIP,@FECHA,@CANTI,@MIN,@PRECIO,@DESC,@V_CODE)


INSERT_PRODUCT '35RR721', 'SERRUCHO', '2014/03/06', 25, 15, 258, 25, 25600