DECLARE @M INT, @MES VARCHAR(20)
SET @M = 4
SET @MES = (CASE @M
WHEN 1 THEN 'ENERO'
WHEN 2 THEN 'FEBRERO'
WHEN 3 THEN 'MARZO'
WHEN 4 THEN 'ABRIL'
WHEN 5 THEN 'MAYO'
WHEN 6 THEN 'JUNIO'
WHEN 7 THEN 'JULIO'
WHEN 8 THEN 'AGOSTO'
WHEN 9 THEN 'SETIEMBRE'
WHEN 10 THEN 'OCTUBRE'
WHEN 11 THEN 'NOVIEMBRE'
WHEN 12 THEN 'DICIEMBRE'
ELSE 'NO ES MES VALIDO'
END)
PRINT @MES

/*Ejercicio sobre  estructura CASE. Modificar o hacer uso del ejemplo de clase para elaborar una función 
que reciba como argumento un número y nos imprima el correspondiente mes.*/

GO
CREATE FUNCTION DBO.MES (@NUMBER INT) RETURNS VARCHAR(50)
AS
BEGIN
DECLARE @MES VARCHAR(50)
SET @MES = (CASE @NUMBER
WHEN 1 THEN 'ENERO'
WHEN 2 THEN 'FEBRERO'
WHEN 3 THEN 'MARZO'
WHEN 4 THEN 'ABRIL'
WHEN 5 THEN 'MAYO'
WHEN 6 THEN 'JUNIO'
WHEN 7 THEN 'JULIO'
WHEN 8 THEN 'AGOSTO'
WHEN 9 THEN 'SETIEMBRE'
WHEN 10 THEN 'OCTUBRE'
WHEN 11 THEN 'NOVIEMBRE'
WHEN 12 THEN 'DICIEMBRE'
ELSE 'NO ES MES VALIDO'
END)
RETURN @MES 
END

PRINT DBO.MES(5)
