/* Sobre la base de datos mis negocios, elaborar un ejemplo de cursor que haga uso de un insert. 
Elaborar un ejemplo de cursor que haga uso de un update. Elaborar un ejemplo de cursor que haga uso de un delete. */

--INSERT

DECLARE @ID VARCHAR(30)
DECLARE INSER CURSOR
FOR 
SELECT IdCategoria FROM COMPRA.CATEGORIAS
FOR UPDATE
OPEN INSER 
FETCH INSER INTO @ID
IF EXISTS (SELECT * FROM COMPRA.CATEGORIAS WHERE IdCategoria = 30)
BEGIN
PRINT 'YA EXISTE'
END 
ELSE INSERT INTO COMPRA.CATEGORIAS (idCategoria,NombreCategoria,Descripcion) VALUES (30,'Decima','Limpia Pisos') 
CLOSE INSER
DEALLOCATE INSER 

SELECT * FROM COMPRA.CATEGORIAS

--UPDATE

DECLARE @Cargo varchar(30)
DECLARE UPDAT CURSOR
FOR 
SELECT desCargo FROM RRHH.CARGOS where desCargo Like 'gerente%'
FOR UPDATE
OPEN UPDAT 
FETCH UPDAT INTO @Cargo
WHILE @@FETCH_STATUS = 0
BEGIN
SET @Cargo = 'Pasante'
UPDATE RRHH.CARGOS SET desCargo = @Cargo WHERE CURRENT OF UPDAT FETCH UPDAT INTO @Cargo
END 
CLOSE UPDAT
DEALLOCATE UPDAT 

SELECT * FROM RRHH.CARGOS

--DELETE

DECLARE @Tipo VARCHAR(30)
DECLARE DEL CURSOR
FOR 
SELECT IdCategoria FROM COMPRA.CATEGORIAS
FOR UPDATE
OPEN DEL 
FETCH DEL INTO @Tipo
WHILE EXISTS (SELECT * FROM COMPRA.CATEGORIAS WHERE IdCategoria = @Tipo)
BEGIN
SET @Tipo = 1
DELETE COMPRA.CATEGORIAS WHERE IdCategoria = @Tipo 
END 
CLOSE DEL
DEALLOCATE DEL 

SELECT * FROM COMPRA.CATEGORIAS