SELECT * FROM EMPLOYEE WHERE year(EMP_HIRE_DATE) = 1993

SELECT * FROM PRODUCT WHERE V_CODE = 21225 AND YEAR(P_INDATE) = 2009

SELECT * FROM EMPLOYEE WHERE EMP_YEARS BETWEEN 14 AND 16

SELECT PART_DESCRIPT FROM PART WHERE V_CODE = 21225

SELECT PART_DESCRIPT, EMP_FNAME,  EMP_LNAME, V_CODE FROM EMPLOYEE,PART WHERE PART.PART_DESCRIPT = 'B&D cordless drill, 1/2-in.'

DECLARE @NUM INT SET @NUM=15 PRINT 'EL NUMERO INGRESADO ES:' + STR(@NUM)

SELECT COUNT(*) AS cantidad FROM PRODUCT 

DECLARE @NUME INT SET @NUME=(SELECT COUNT(*) FROM PRODUCT AS cantidad) PRINT 'EL NUMERO DE REGISTROS ES:' + STR(@NUME)

DECLARE @max_value FLOAT SET @max_value = (SELECT MAX(p_price) FROM PRODUCT AS mayor_venta) SELECT @max_value, V_CODE FROM PRODUCT WHERE (P_PRICE >= @max_value)

SELECT COUNT(CUS_AREACODE) AS Repeticiones, CUS_AREACODE AS Numero_De_Codigos FROM CUSTOMER GROUP BY CUS_AREACODE

SELECT * FROM PART
SELECT * FROM PRODUCT

