CREATE FUNCTION DBO.VentaPrdocutos(@Num_Producto VARCHAR(10), @CANTIDAD INT, @CUS_NUMBER INT, @CUS_LNAME VARCHAR(50), @CUS_FNAME VARCHAR(50), @PAGO DECIMAL) 
RETURNS @TABLA TABLE(
ACCT_TRANS_NUM INT,
ACCT_TRANS_DATE DATETIME,
CUST_NUMBER INT,
ACCT_TRANS_TYPE NVARCHAR(8),
ACCT_TRANS_AMOUNT REAL,
CUS_NUMBER INT NULL,
CUS_LNAME NVARCHAR(15) NULL,
CUS_FNAME  NVARCHAR(15) NULL,
CUS_INITIAL  NVARCHAR(1) NULL,
CUS_ARECODE  NVARCHAR(3) NULL,
CUS_PHONE  NVARCHAR(8) NULL,
CUS_BALANCE REAL NULL)
AS
BEGIN 
	IF (((SELECT PROD_QOH FROM PRODUCT) - @CANTIDAD) = 0)
		BEGIN
			PRINT 'NO EXISTE LA CANTIDAD DE PRODUCTOS'
		END
	ELSE IF(((SELECT PROD_PRICE FROM PRODUCT WHERE PROD_CODE = @Num_Producto) * @CANTIDAD) > @PAGO)
		BEGIN
			PRINT 'FALTA DINERO PARA LA COMPRA'
		END
	ELSE IF(@CANTIDAD > 1 AND ((SELECT PROD_PRICE FROM PRODUCT WHERE PROD_CODE = @Num_Producto) * @CANTIDAD) < @PAGO)
		BEGIN

			IF EXISTS(SELECT * FROM CUSTOMER WHERE CUST_NUMBER = @Num_Producto)
			BEGIN
				UPDATE CUSTOMER SET CUST_BALANCE = (((SELECT PROD_PRICE FROM PRODUCT WHERE PROD_CODE = @Num_Producto) * @CANTIDAD) - @PAGO) WHERE CUST_NUMBER = @CUS_NUMBER
			END
			ELSE
				BEGIN
					INSERT INTO @TABLA (CUS_LNAME,CUS_FNAME,CUS_INITIAL,CUS_ARECODE,CUS_PHONE,CUS_BALANCE) VALUES (@CUS_NUMBER,@CUS_LNAME,@CUS_FNAME,NULL,NULL,NULL,(((SELECT PROD_PRICE FROM PRODUCT WHERE PROD_CODE = @Num_Producto) * @CANTIDAD) - @PAGO))
				END
			UPDATE PRODUCT SET PROD_QOH = ((SELECT PROD_QOH FROM PRODUCT WHERE PROD_CODE = @Num_Producto) - @CANTIDAD)
			INSERT INTO @TABLA (ACCT_TRANS_NUM,ACCT_TRANS_DATE,CUS_NUMBER,ACCT_TRANS_TYPE,ACCT_TRANS_AMOUNT) VALUES(@Num_Producto,GETDATE (),@CUS_NUMBER,'payment',@PAGO)
			DECLARE @DEVOL VARCHAR(500)
			SET @DEVOL =  STR((((SELECT PROD_PRICE FROM PRODUCT WHERE PROD_CODE = @Num_Producto) * @CANTIDAD) - @PAGO))
			PRINT 'SU CAMBIO ES: ' + @DEVOL
		END
	ELSE
	ROLLBACK
RETURN
END
GO

SELECT DBO.VentaPrdocutos('11QER/31',3,10010,'Ramas','Alfred',500) 