
---Crear Trigger---
CREATE TRIGGER TX_Productos
ON COMPRA.PRODUCTOS
FOR INSERT,UPDATE,DELETE
AS
PRINT 'Actualizacion de los registros de productos.'
GO

---Prueba---
UPDATE COMPRA.PRODUCTOS SET precioUnidad = precioUnidad + precioUnidad* .15 WHERE IdProducto = 2
GO

---Modificar---
ALTER TRIGGER COMPRA.TX_Productos
ON COMPRA.PRODUCTOS
FOR INSERT,UPDATE,DELETE
AS
PRINT 'ACTUALIZACION.'
GO

---Borrar---
DROP TRIGGER COMPRA.TX_Productos
GO

---Seguridad---
CREATE TRIGGER TX_PRODUCTO_INSERTA
ON COMPRA.PRODUCTOS
FOR INSERT
AS
IF (SELECT COUNT(*) FROM INSERTED, COMPRA.PRODUCTOS WHERE INSERTED.NOMPRODUCTO = COMPRA.PRODUCTOS.nomProducto) > 1
BEGIN
ROLLBACK TRANSACTION
PRINT 'EL NOMBRE DEL PRODUCTO SE ENCUENTRA REGISTRADO'
END
ELSE
PRINT 'EL PRODUCTO FUE INGRESADO EN LA BASE DE DATOS'
GO

---Insert---
INSERT INTO COMPRA.PRODUCTOS (IdProducto, nomProducto, idProveedor, idCategoria, cantxUnidad, precioUnidad, UniEnExistencia, UniEnPedido)
VALUES(10, 'Detergente líquido', 5, 3, 150, 2500, 5000, 36);
GO

---Delete---
CREATE TRIGGER TX_ELIMINA2
ON VENDOR
FOR DELETE
AS
IF EXISTS (SELECT * FROM PRODUCT WHERE V_CODE = (SELECT V_CODE FROM DELETED))
BEGIN
DELETE FROM VENDOR WHERE V_CODE = (SELECT V_CODE FROM DELETED)
ROLLBACK TRANSACTION
PRINT 'EL VENDEDOR HA REALIZADO VENTAS'
END
GO

---Delete---

DELETE FROM VENDOR WHERE V_CODE = 21226
GO
SELECT VENDOR.* FROM VENDOR WHERE NOT EXISTS(SELECT NULL FROM PRODUCT WHERE VENDOR.V_CODE  = PRODUCT.V_CODE)
GO

---TRIGGER DELETE---
CREATE TRIGGER TX_PRODUCTO_ACTUALIZA
ON PRODUCT
FOR UPDATE
AS
IF (SELECT P_PRICE FROM INSERTED) <= 0 OR (SELECT P_QOH FROM INSERTED) <= 0
BEGIN
PRINT ' EL PRECIO O LA CANTIDAD DEBE SER MAYOR A CERO '
ROLLBACK TRANSACTION
END
GO

---Delete2---

UPDATE PRODUCT SET P_PRICE = 0 WHERE P_CODE = '11QER/31'
GO
UPDATE PRODUCT SET P_QOH = 0 WHERE P_CODE = '11QER/31'

GO

CREATE TRIGGER TX_PRODUCTO_ACTUALIZA_FECHA_
ON INVOICE
FOR UPDATE
AS
IF (SELECT INV_DATE FROM INSERTED) > 2010-12-31
BEGIN
PRINT ' LA FECHA DE LA FACTURA DEBE SER MENOR AL 2010 '
ROLLBACK TRANSACTION
END
GO

UPDATE INVOICE SET INV_DATE = '2010-02-12' WHERE INV_NUMBER = 1008